
# This file is automatically generated, you probably don't want to edit this

ttestOneSOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ttestOneSOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            calc = "n",
            es = 0.5,
            power = 0.9,
            n = 20,
            alt = "two.sided",
            alpha = 0.05,
            powerContour = TRUE,
            powerDist = FALSE,
            powerCurveES = TRUE,
            powerCurveN = FALSE,
            text = TRUE, ...) {

            super$initialize(
                package="jpower",
                name="ttestOneS",
                requiresData=FALSE,
                ...)

            private$..calc <- jmvcore::OptionList$new(
                "calc",
                calc,
                options=list(
                    "n",
                    "power",
                    "es"),
                default="n")
            private$..es <- jmvcore::OptionNumber$new(
                "es",
                es,
                min=0.01,
                default=0.5)
            private$..power <- jmvcore::OptionNumber$new(
                "power",
                power,
                min=0,
                max=1,
                default=0.9)
            private$..n <- jmvcore::OptionInteger$new(
                "n",
                n,
                min=2,
                default=20)
            private$..alt <- jmvcore::OptionList$new(
                "alt",
                alt,
                options=list(
                    "two.sided",
                    "less",
                    "greater"),
                default="two.sided")
            private$..alpha <- jmvcore::OptionNumber$new(
                "alpha",
                alpha,
                min=0,
                default=0.05)
            private$..powerContour <- jmvcore::OptionBool$new(
                "powerContour",
                powerContour,
                default=TRUE)
            private$..powerDist <- jmvcore::OptionBool$new(
                "powerDist",
                powerDist,
                default=FALSE)
            private$..powerCurveES <- jmvcore::OptionBool$new(
                "powerCurveES",
                powerCurveES,
                default=TRUE)
            private$..powerCurveN <- jmvcore::OptionBool$new(
                "powerCurveN",
                powerCurveN,
                default=FALSE)
            private$..text <- jmvcore::OptionBool$new(
                "text",
                text,
                default=TRUE)

            self$.addOption(private$..calc)
            self$.addOption(private$..es)
            self$.addOption(private$..power)
            self$.addOption(private$..n)
            self$.addOption(private$..alt)
            self$.addOption(private$..alpha)
            self$.addOption(private$..powerContour)
            self$.addOption(private$..powerDist)
            self$.addOption(private$..powerCurveES)
            self$.addOption(private$..powerCurveN)
            self$.addOption(private$..text)
        }),
    active = list(
        calc = function() private$..calc$value,
        es = function() private$..es$value,
        power = function() private$..power$value,
        n = function() private$..n$value,
        alt = function() private$..alt$value,
        alpha = function() private$..alpha$value,
        powerContour = function() private$..powerContour$value,
        powerDist = function() private$..powerDist$value,
        powerCurveES = function() private$..powerCurveES$value,
        powerCurveN = function() private$..powerCurveN$value,
        text = function() private$..text$value),
    private = list(
        ..calc = NA,
        ..es = NA,
        ..power = NA,
        ..n = NA,
        ..alt = NA,
        ..alpha = NA,
        ..powerContour = NA,
        ..powerDist = NA,
        ..powerCurveES = NA,
        ..powerCurveN = NA,
        ..text = NA)
)

ttestOneSResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ttestOneSResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="One Sample T-Test")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="One Sample T-Test"))}))

ttestOneSBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ttestOneSBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jpower",
                name = "ttestOneS",
                version = c(1,0,0),
                options = options,
                results = ttestOneSResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' One Sample T-Test
#'
#' 
#' @param calc .
#' @param es .
#' @param power .
#' @param n .
#' @param alt .
#' @param alpha .
#' @param powerContour .
#' @param powerDist .
#' @param powerCurveES .
#' @param powerCurveN .
#' @param text .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
ttestOneS <- function(
    calc = "n",
    es = 0.5,
    power = 0.9,
    n = 20,
    alt = "two.sided",
    alpha = 0.05,
    powerContour = TRUE,
    powerDist = FALSE,
    powerCurveES = TRUE,
    powerCurveN = FALSE,
    text = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("ttestOneS requires jmvcore to be installed (restart may be required)")


    options <- ttestOneSOptions$new(
        calc = calc,
        es = es,
        power = power,
        n = n,
        alt = alt,
        alpha = alpha,
        powerContour = powerContour,
        powerDist = powerDist,
        powerCurveES = powerCurveES,
        powerCurveN = powerCurveN,
        text = text)

    analysis <- ttestOneSClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

