
# This file is automatically generated, you probably don't want to edit this

#' @importFrom jmvcore Options
#' @importFrom R6 R6Class
anovaOptions <- R6::R6Class(
    "anovaOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            estype = "<i>f</i>",
            es = 0.3,
            power = 0.8,
            n = 20,
            k = 3,
            alpha = 0.05, ...) {

            super$initialize(
                package='jpower',
                name='anova',
                requiresData=TRUE,
                ...)
        
            private$..estype <- jmvcore::OptionList$new(
                "estype",
                estype,
                options=list(
                    "<i>f</i>",
                    "<i>&omega;<sup>2</sup></i>"),
                default="<i>f</i>")
            private$..es <- jmvcore::OptionNumber$new(
                "es",
                es,
                min=0,
                default=0.3)
            private$..power <- jmvcore::OptionNumber$new(
                "power",
                power,
                min=0,
                max=1,
                default=0.8)
            private$..n <- jmvcore::OptionInteger$new(
                "n",
                n,
                min=2,
                default=20)
            private$..k <- jmvcore::OptionInteger$new(
                "k",
                k,
                min=2,
                default=3)
            private$..alpha <- jmvcore::OptionNumber$new(
                "alpha",
                alpha,
                min=0,
                default=0.05)
        
            self$.addOption(private$..estype)
            self$.addOption(private$..es)
            self$.addOption(private$..power)
            self$.addOption(private$..n)
            self$.addOption(private$..k)
            self$.addOption(private$..alpha)
        }),
    active = list(
        estype = function() private$..estype$value,
        es = function() private$..es$value,
        power = function() private$..power$value,
        n = function() private$..n$value,
        k = function() private$..k$value,
        alpha = function() private$..alpha$value),
    private = list(
        ..estype = NA,
        ..es = NA,
        ..power = NA,
        ..n = NA,
        ..k = NA,
        ..alpha = NA)
)

#' @import jmvcore
#' @importFrom R6 R6Class
anovaResults <- R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        powertab = function() private$..powertab,
        powerDist = function() private$..powerDist,
        powercurveES = function() private$..powercurveES,
        powercurveN = function() private$..powercurveN),
    private = list(
        ..powertab = NA,
        ..powerDist = NA,
        ..powercurveES = NA,
        ..powercurveN = NA),
    public=list(
        initialize=function(options) {
            super$initialize(options=options, name="", title="ANOVA")
            private$..powertab <- jmvcore::Table$new(
                options=options,
                name="powertab",
                title="A priori power analysis",
                rows=4,
                columns=list(
                    list(`name`="var", `title`="", `type`="text"),
                    list(`name`="val", `type`="number", `title`="")))
            private$..powerDist <- jmvcore::Image$new(
                options=options,
                name="powerDist",
                title="Power demonstration",
                width=400,
                height=300,
                renderFun=".powerDist")
            private$..powercurveES <- jmvcore::Image$new(
                options=options,
                name="powercurveES",
                title="Power curve by effect size",
                width=400,
                height=300,
                renderFun=".powercurveES")
            private$..powercurveN <- jmvcore::Image$new(
                options=options,
                name="powercurveN",
                title="Power curve by N",
                width=400,
                height=300,
                renderFun=".powercurveN")
            self$add(private$..powertab)
            self$add(private$..powerDist)
            self$add(private$..powercurveES)
            self$add(private$..powercurveN)}))

#' @importFrom jmvcore Analysis
#' @importFrom R6 R6Class
anovaBase <- R6::R6Class(
    "anovaBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'jpower',
                name = 'anova',
                version = c(1,0,0),
                options = options,
                results = anovaResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL)
        }))

#' ANOVA
#'
#' 
#' @param estype .
#' @param es .
#' @param power .
#' @param n .
#' @param k .
#' @param alpha .
#' @export
anova <- function(
    estype = "<i>f</i>",
    es = 0.3,
    power = 0.8,
    n = 20,
    k = 3,
    alpha = 0.05) {

    options <- anovaOptions$new(
        estype = estype,
        es = es,
        power = power,
        n = n,
        k = k,
        alpha = alpha)

    results <- anovaResults$new(
        options = options)

    analysis <- anovaClass$new(
        options = options,
        data = data)

    analysis$run()
    analysis$render()

    analysis
}
