
# This file is automatically generated, you probably don't want to edit this

anovaOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "anovaOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            lev_fac_a = 3,
            lev_fac_b = 2,
            lev_fac_c = 2,
            type_fac_a = "b",
            type_fac_b = "b",
            type_fac_c = "b",
            power = 0.8,
            n = 20,
            alpha = 0.05,
            powerDist = FALSE,
            powerCurveES = FALSE,
            powerCurveN = FALSE,
            findN = FALSE,
            num_facs = "one",
            eff_fac_a = 0,
            eff_fac_b = 0,
            eff_fac_c = 0,
            eff_fac_ab = 0,
            eff_fac_bc = 0,
            eff_fac_ac = 0,
            eff_fac_abc = 0,
            min_n = 3,
            max_n = 100, ...) {

            super$initialize(
                package="jpower",
                name="anova",
                requiresData=FALSE,
                ...)

            private$..lev_fac_a <- jmvcore::OptionInteger$new(
                "lev_fac_a",
                lev_fac_a,
                min=2,
                default=3)
            private$..lev_fac_b <- jmvcore::OptionInteger$new(
                "lev_fac_b",
                lev_fac_b,
                min=2,
                max=99,
                default=2)
            private$..lev_fac_c <- jmvcore::OptionInteger$new(
                "lev_fac_c",
                lev_fac_c,
                min=2,
                max=99,
                default=2)
            private$..type_fac_a <- jmvcore::OptionList$new(
                "type_fac_a",
                type_fac_a,
                options=list(
                    "b",
                    "w"),
                default="b")
            private$..type_fac_b <- jmvcore::OptionList$new(
                "type_fac_b",
                type_fac_b,
                options=list(
                    "b",
                    "w"),
                default="b")
            private$..type_fac_c <- jmvcore::OptionList$new(
                "type_fac_c",
                type_fac_c,
                options=list(
                    "b",
                    "w"),
                default="b")
            private$..power <- jmvcore::OptionNumber$new(
                "power",
                power,
                min=0,
                max=1,
                default=0.8)
            private$..n <- jmvcore::OptionInteger$new(
                "n",
                n,
                min=2,
                default=20)
            private$..alpha <- jmvcore::OptionNumber$new(
                "alpha",
                alpha,
                min=0,
                default=0.05)
            private$..powerDist <- jmvcore::OptionBool$new(
                "powerDist",
                powerDist,
                default=FALSE)
            private$..powerCurveES <- jmvcore::OptionBool$new(
                "powerCurveES",
                powerCurveES,
                default=FALSE)
            private$..powerCurveN <- jmvcore::OptionBool$new(
                "powerCurveN",
                powerCurveN,
                default=FALSE)
            private$..findN <- jmvcore::OptionBool$new(
                "findN",
                findN,
                default=FALSE)
            private$..num_facs <- jmvcore::OptionList$new(
                "num_facs",
                num_facs,
                options=list(
                    "one",
                    "two",
                    "three"),
                default="one")
            private$..eff_fac_a <- jmvcore::OptionNumber$new(
                "eff_fac_a",
                eff_fac_a,
                min=0,
                max=70.70537,
                default=0)
            private$..eff_fac_b <- jmvcore::OptionNumber$new(
                "eff_fac_b",
                eff_fac_b,
                min=0,
                max=70.70537,
                default=0)
            private$..eff_fac_c <- jmvcore::OptionNumber$new(
                "eff_fac_c",
                eff_fac_c,
                min=0,
                max=70.70537,
                default=0)
            private$..eff_fac_ab <- jmvcore::OptionNumber$new(
                "eff_fac_ab",
                eff_fac_ab,
                min=0,
                max=70.70537,
                default=0)
            private$..eff_fac_bc <- jmvcore::OptionNumber$new(
                "eff_fac_bc",
                eff_fac_bc,
                min=0,
                max=70.70537,
                default=0)
            private$..eff_fac_ac <- jmvcore::OptionNumber$new(
                "eff_fac_ac",
                eff_fac_ac,
                min=0,
                max=70.70537,
                default=0)
            private$..eff_fac_abc <- jmvcore::OptionNumber$new(
                "eff_fac_abc",
                eff_fac_abc,
                min=0,
                max=70.70537,
                default=0)
            private$..min_n <- jmvcore::OptionInteger$new(
                "min_n",
                min_n,
                min=3,
                default=3)
            private$..max_n <- jmvcore::OptionInteger$new(
                "max_n",
                max_n,
                min=4,
                default=100)

            self$.addOption(private$..lev_fac_a)
            self$.addOption(private$..lev_fac_b)
            self$.addOption(private$..lev_fac_c)
            self$.addOption(private$..type_fac_a)
            self$.addOption(private$..type_fac_b)
            self$.addOption(private$..type_fac_c)
            self$.addOption(private$..power)
            self$.addOption(private$..n)
            self$.addOption(private$..alpha)
            self$.addOption(private$..powerDist)
            self$.addOption(private$..powerCurveES)
            self$.addOption(private$..powerCurveN)
            self$.addOption(private$..findN)
            self$.addOption(private$..num_facs)
            self$.addOption(private$..eff_fac_a)
            self$.addOption(private$..eff_fac_b)
            self$.addOption(private$..eff_fac_c)
            self$.addOption(private$..eff_fac_ab)
            self$.addOption(private$..eff_fac_bc)
            self$.addOption(private$..eff_fac_ac)
            self$.addOption(private$..eff_fac_abc)
            self$.addOption(private$..min_n)
            self$.addOption(private$..max_n)
        }),
    active = list(
        lev_fac_a = function() private$..lev_fac_a$value,
        lev_fac_b = function() private$..lev_fac_b$value,
        lev_fac_c = function() private$..lev_fac_c$value,
        type_fac_a = function() private$..type_fac_a$value,
        type_fac_b = function() private$..type_fac_b$value,
        type_fac_c = function() private$..type_fac_c$value,
        power = function() private$..power$value,
        n = function() private$..n$value,
        alpha = function() private$..alpha$value,
        powerDist = function() private$..powerDist$value,
        powerCurveES = function() private$..powerCurveES$value,
        powerCurveN = function() private$..powerCurveN$value,
        findN = function() private$..findN$value,
        num_facs = function() private$..num_facs$value,
        eff_fac_a = function() private$..eff_fac_a$value,
        eff_fac_b = function() private$..eff_fac_b$value,
        eff_fac_c = function() private$..eff_fac_c$value,
        eff_fac_ab = function() private$..eff_fac_ab$value,
        eff_fac_bc = function() private$..eff_fac_bc$value,
        eff_fac_ac = function() private$..eff_fac_ac$value,
        eff_fac_abc = function() private$..eff_fac_abc$value,
        min_n = function() private$..min_n$value,
        max_n = function() private$..max_n$value),
    private = list(
        ..lev_fac_a = NA,
        ..lev_fac_b = NA,
        ..lev_fac_c = NA,
        ..type_fac_a = NA,
        ..type_fac_b = NA,
        ..type_fac_c = NA,
        ..power = NA,
        ..n = NA,
        ..alpha = NA,
        ..powerDist = NA,
        ..powerCurveES = NA,
        ..powerCurveN = NA,
        ..findN = NA,
        ..num_facs = NA,
        ..eff_fac_a = NA,
        ..eff_fac_b = NA,
        ..eff_fac_c = NA,
        ..eff_fac_ab = NA,
        ..eff_fac_bc = NA,
        ..eff_fac_ac = NA,
        ..eff_fac_abc = NA,
        ..min_n = NA,
        ..max_n = NA)
)

anovaResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "anovaResults",
    inherit = jmvcore::Group,
    active = list(
        intro = function() private$.items[["intro"]],
        designtab = function() private$.items[["designtab"]],
        text1 = function() private$.items[["text1"]],
        main = function() private$.items[["main"]],
        text2 = function() private$.items[["text2"]],
        tabN = function() private$.items[["tabN"]],
        powerDist = function() private$.items[["powerDist"]],
        distText = function() private$.items[["distText"]],
        powerCurveES = function() private$.items[["powerCurveES"]],
        powerCurveN = function() private$.items[["powerCurveN"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="ANOVA (imputed effect sizes)")
            self$add(jmvcore::Html$new(
                options=options,
                name="intro",
                title="Introduction",
                visible="(text)"))
            self$add(jmvcore::Table$new(
                options=options,
                name="designtab",
                title="Design",
                rows=1,
                clearWith=list(
                    "lev_fac_a",
                    "lev_fac_b",
                    "lev_fac_c",
                    "type_fac_a",
                    "type_fac_b",
                    "type_fac_c",
                    "n"),
                columns=list(
                    list(
                        `name`="var[type]", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="var[des]", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="var[n]", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="var[n_obs]", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="var[n_tot]", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="val[type]", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="val[des]", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="val[n]", 
                        `title`="", 
                        `type`="integer"),
                    list(
                        `name`="val[n_obs]", 
                        `title`="", 
                        `type`="integer"),
                    list(
                        `name`="val[n_tot]", 
                        `title`="", 
                        `type`="integer"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="text1",
                visible="(text)"))
            self$add(jmvcore::Table$new(
                options=options,
                name="main",
                title="Factorial ANOVA Power Analysis",
                clearWith=list(
                    "n",
                    "alpha",
                    "lev_fac_c",
                    "lev_fac_b",
                    "lev_fac_a",
                    "type_fac_c",
                    "type_fac_b",
                    "type_fac_a",
                    "eff_fac_c",
                    "eff_fac_b",
                    "eff_fac_a",
                    "eff_fac_ab",
                    "eff_fac_bc",
                    "eff_fac_ac",
                    "eff_fac_abc",
                    "num_facs"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="num_df", 
                        `title`="Numerator DF", 
                        `type`="integer"),
                    list(
                        `name`="den_df", 
                        `title`="Denominator DF", 
                        `type`="integer"),
                    list(
                        `name`="cohen_f", 
                        `title`="Cohen's f", 
                        `type`="number"),
                    list(
                        `name`="alpha_level", 
                        `title`="Alpha Level", 
                        `type`="number"),
                    list(
                        `name`="power", 
                        `title`="Power (1-Beta)", 
                        `type`="number"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="text2",
                visible="(findN)"))
            self$add(jmvcore::Table$new(
                options=options,
                name="tabN",
                title="N for Desired Power",
                visible="(findN)",
                clearWith=list(
                    "alpha",
                    "lev_fac_c",
                    "lev_fac_b",
                    "lev_fac_a",
                    "type_fac_c",
                    "type_fac_b",
                    "type_fac_a",
                    "eff_fac_c",
                    "eff_fac_b",
                    "eff_fac_a",
                    "eff_fac_ab",
                    "eff_fac_bc",
                    "eff_fac_ac",
                    "eff_fac_abc",
                    "num_facs",
                    "min_n",
                    "max_n"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="n", 
                        `title`="N per group", 
                        `type`="integer"),
                    list(
                        `name`="power", 
                        `title`="Estimated Power", 
                        `type`="number"),
                    list(
                        `name`="label", 
                        `title`="", 
                        `type`="text"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="powerDist",
                title="Power Demonstration",
                width=600,
                height=600,
                renderFun=".powerDist",
                visible="(powerDist)",
                clearWith=list(
                    "dep",
                    "num_facs",
                    "alpha",
                    "lev_fac_c",
                    "lev_fac_b",
                    "lev_fac_a",
                    "type_fac_c",
                    "type_fac_b",
                    "type_fac_a",
                    "eff_fac_c",
                    "eff_fac_b",
                    "eff_fac_a",
                    "eff_fac_ab",
                    "eff_fac_bc",
                    "eff_fac_ac",
                    "eff_fac_abc")))
            self$add(jmvcore::Html$new(
                options=options,
                name="distText",
                title="Power contour context",
                visible="(powerDist)"))
            self$add(jmvcore::Image$new(
                options=options,
                name="powerCurveES",
                title="Power Curve by Effect Size",
                width=600,
                height=600,
                renderFun=".powerCurveES",
                visible="(powerCurveES)",
                clearWith=list(
                    "power",
                    "lev_fac_c",
                    "lev_fac_b",
                    "lev_fac_a",
                    "type_fac_c",
                    "type_fac_b",
                    "type_fac_a",
                    "dep",
                    "num_facs",
                    "n")))
            self$add(jmvcore::Image$new(
                options=options,
                name="powerCurveN",
                title="Power Curve by N",
                width=600,
                height=600,
                renderFun=".powerCurveN",
                visible="(powerCurveN)",
                clearWith=list(
                    "power",
                    "lev_fac_c",
                    "lev_fac_b",
                    "lev_fac_a",
                    "type_fac_c",
                    "type_fac_b",
                    "type_fac_a",
                    "eff_fac_c",
                    "eff_fac_b",
                    "eff_fac_a",
                    "eff_fac_ab",
                    "eff_fac_bc",
                    "eff_fac_ac",
                    "eff_fac_abc",
                    "max_n",
                    "min_n",
                    "alpha",
                    "dep")))}))

anovaBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "anovaBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jpower",
                name = "anova",
                version = c(1,0,0),
                options = options,
                results = anovaResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Factorial ANOVA
#'
#' 
#' @param lev_fac_a .
#' @param lev_fac_b .
#' @param lev_fac_c .
#' @param type_fac_a .
#' @param type_fac_b .
#' @param type_fac_c .
#' @param power .
#' @param n .
#' @param alpha .
#' @param powerDist .
#' @param powerCurveES .
#' @param powerCurveN .
#' @param findN .
#' @param num_facs .
#' @param eff_fac_a .
#' @param eff_fac_b .
#' @param eff_fac_c .
#' @param eff_fac_ab .
#' @param eff_fac_bc .
#' @param eff_fac_ac .
#' @param eff_fac_abc .
#' @param min_n .
#' @param max_n .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$intro} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$designtab} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$text1} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$main} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$text2} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$tabN} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$powerDist} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$distText} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$powerCurveES} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$powerCurveN} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$designtab$asDF}
#'
#' \code{as.data.frame(results$designtab)}
#'
#' @export
anova <- function(
    lev_fac_a = 3,
    lev_fac_b = 2,
    lev_fac_c = 2,
    type_fac_a = "b",
    type_fac_b = "b",
    type_fac_c = "b",
    power = 0.8,
    n = 20,
    alpha = 0.05,
    powerDist = FALSE,
    powerCurveES = FALSE,
    powerCurveN = FALSE,
    findN = FALSE,
    num_facs = "one",
    eff_fac_a = 0,
    eff_fac_b = 0,
    eff_fac_c = 0,
    eff_fac_ab = 0,
    eff_fac_bc = 0,
    eff_fac_ac = 0,
    eff_fac_abc = 0,
    min_n = 3,
    max_n = 100) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("anova requires jmvcore to be installed (restart may be required)")


    options <- anovaOptions$new(
        lev_fac_a = lev_fac_a,
        lev_fac_b = lev_fac_b,
        lev_fac_c = lev_fac_c,
        type_fac_a = type_fac_a,
        type_fac_b = type_fac_b,
        type_fac_c = type_fac_c,
        power = power,
        n = n,
        alpha = alpha,
        powerDist = powerDist,
        powerCurveES = powerCurveES,
        powerCurveN = powerCurveN,
        findN = findN,
        num_facs = num_facs,
        eff_fac_a = eff_fac_a,
        eff_fac_b = eff_fac_b,
        eff_fac_c = eff_fac_c,
        eff_fac_ab = eff_fac_ab,
        eff_fac_bc = eff_fac_bc,
        eff_fac_ac = eff_fac_ac,
        eff_fac_abc = eff_fac_abc,
        min_n = min_n,
        max_n = max_n)

    analysis <- anovaClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

