
# This file is automatically generated, you probably don't want to edit this

anovaOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "anovaOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            lev_fac_a = 3,
            lev_fac_b = 0,
            lev_fac_c = 0,
            type_fac_a = "b",
            type_fac_b = "b",
            type_fac_c = "b",
            estype = "f",
            es = 0.3,
            power = 0.8,
            n = 20,
            k = 3,
            alpha = 0.05,
            powerDist = TRUE,
            powerCurveES = FALSE,
            powerCurveN = FALSE,
            num_facs = "one", ...) {

            super$initialize(
                package="jpower",
                name="anova",
                requiresData=FALSE,
                ...)

            private$..lev_fac_a <- jmvcore::OptionInteger$new(
                "lev_fac_a",
                lev_fac_a,
                min=2,
                default=3)
            private$..lev_fac_b <- jmvcore::OptionInteger$new(
                "lev_fac_b",
                lev_fac_b,
                min=0,
                max=99,
                default=0)
            private$..lev_fac_c <- jmvcore::OptionInteger$new(
                "lev_fac_c",
                lev_fac_c,
                min=0,
                max=99,
                default=0)
            private$..type_fac_a <- jmvcore::OptionList$new(
                "type_fac_a",
                type_fac_a,
                options=list(
                    "b",
                    "w"),
                default="b")
            private$..type_fac_b <- jmvcore::OptionList$new(
                "type_fac_b",
                type_fac_b,
                options=list(
                    "b",
                    "w"),
                default="b")
            private$..type_fac_c <- jmvcore::OptionList$new(
                "type_fac_c",
                type_fac_c,
                options=list(
                    "b",
                    "w"),
                default="b")
            private$..estype <- jmvcore::OptionList$new(
                "estype",
                estype,
                options=list(
                    "f",
                    "omega"),
                default="f")
            private$..es <- jmvcore::OptionNumber$new(
                "es",
                es,
                min=0,
                default=0.3)
            private$..power <- jmvcore::OptionNumber$new(
                "power",
                power,
                min=0,
                max=1,
                default=0.8)
            private$..n <- jmvcore::OptionInteger$new(
                "n",
                n,
                min=2,
                default=20)
            private$..k <- jmvcore::OptionInteger$new(
                "k",
                k,
                min=2,
                default=3)
            private$..alpha <- jmvcore::OptionNumber$new(
                "alpha",
                alpha,
                min=0,
                default=0.05)
            private$..powerDist <- jmvcore::OptionBool$new(
                "powerDist",
                powerDist,
                default=TRUE)
            private$..powerCurveES <- jmvcore::OptionBool$new(
                "powerCurveES",
                powerCurveES,
                default=FALSE)
            private$..powerCurveN <- jmvcore::OptionBool$new(
                "powerCurveN",
                powerCurveN,
                default=FALSE)
            private$..num_facs <- jmvcore::OptionList$new(
                "num_facs",
                num_facs,
                options=list(
                    "one",
                    "two",
                    "three"),
                default="one")

            self$.addOption(private$..lev_fac_a)
            self$.addOption(private$..lev_fac_b)
            self$.addOption(private$..lev_fac_c)
            self$.addOption(private$..type_fac_a)
            self$.addOption(private$..type_fac_b)
            self$.addOption(private$..type_fac_c)
            self$.addOption(private$..estype)
            self$.addOption(private$..es)
            self$.addOption(private$..power)
            self$.addOption(private$..n)
            self$.addOption(private$..k)
            self$.addOption(private$..alpha)
            self$.addOption(private$..powerDist)
            self$.addOption(private$..powerCurveES)
            self$.addOption(private$..powerCurveN)
            self$.addOption(private$..num_facs)
        }),
    active = list(
        lev_fac_a = function() private$..lev_fac_a$value,
        lev_fac_b = function() private$..lev_fac_b$value,
        lev_fac_c = function() private$..lev_fac_c$value,
        type_fac_a = function() private$..type_fac_a$value,
        type_fac_b = function() private$..type_fac_b$value,
        type_fac_c = function() private$..type_fac_c$value,
        estype = function() private$..estype$value,
        es = function() private$..es$value,
        power = function() private$..power$value,
        n = function() private$..n$value,
        k = function() private$..k$value,
        alpha = function() private$..alpha$value,
        powerDist = function() private$..powerDist$value,
        powerCurveES = function() private$..powerCurveES$value,
        powerCurveN = function() private$..powerCurveN$value,
        num_facs = function() private$..num_facs$value),
    private = list(
        ..lev_fac_a = NA,
        ..lev_fac_b = NA,
        ..lev_fac_c = NA,
        ..type_fac_a = NA,
        ..type_fac_b = NA,
        ..type_fac_c = NA,
        ..estype = NA,
        ..es = NA,
        ..power = NA,
        ..n = NA,
        ..k = NA,
        ..alpha = NA,
        ..powerDist = NA,
        ..powerCurveES = NA,
        ..powerCurveN = NA,
        ..num_facs = NA)
)

anovaResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "anovaResults",
    inherit = jmvcore::Group,
    active = list(
        powertab = function() private$.items[["powertab"]],
        powerDist = function() private$.items[["powerDist"]],
        powerCurveES = function() private$.items[["powerCurveES"]],
        powerCurveN = function() private$.items[["powerCurveN"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="ANOVA")
            self$add(jmvcore::Table$new(
                options=options,
                name="powertab",
                title="A Priori Power Analysis",
                rows=1,
                clearWith=list(
                    "estype",
                    "es",
                    "power",
                    "n",
                    "k",
                    "alpha"),
                columns=list(
                    list(
                        `name`="var[n]", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="var[es]", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="var[power]", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="var[alpha]", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="val[n]", 
                        `title`="", 
                        `type`="integer"),
                    list(
                        `name`="val[es]", 
                        `title`="", 
                        `type`="number"),
                    list(
                        `name`="val[power]", 
                        `title`="", 
                        `type`="number"),
                    list(
                        `name`="val[alpha]", 
                        `title`="", 
                        `type`="number"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="powerDist",
                title="Power Demonstration",
                width=400,
                height=300,
                renderFun=".powerDist",
                visible="(powerDist)",
                clearWith=list(
                    "estype",
                    "es",
                    "power",
                    "n",
                    "k",
                    "alpha")))
            self$add(jmvcore::Image$new(
                options=options,
                name="powerCurveES",
                title="Power Curve by Effect Size",
                width=400,
                height=300,
                renderFun=".powerCurveES",
                visible="(powerCurveES)",
                clearWith=list(
                    "estype",
                    "es",
                    "power",
                    "n",
                    "k",
                    "alpha")))
            self$add(jmvcore::Image$new(
                options=options,
                name="powerCurveN",
                title="Power Curve by N",
                width=400,
                height=300,
                renderFun=".powerCurveN",
                visible="(powerCurveN)",
                clearWith=list(
                    "estype",
                    "es",
                    "power",
                    "n",
                    "k",
                    "alpha")))}))

anovaBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "anovaBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jpower",
                name = "anova",
                version = c(1,0,0),
                options = options,
                results = anovaResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Factorial ANOVA
#'
#' 
#' @param lev_fac_a .
#' @param lev_fac_b .
#' @param lev_fac_c .
#' @param type_fac_a .
#' @param type_fac_b .
#' @param type_fac_c .
#' @param estype .
#' @param es .
#' @param power .
#' @param n .
#' @param k .
#' @param alpha .
#' @param powerDist .
#' @param powerCurveES .
#' @param powerCurveN .
#' @param num_facs .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$powertab} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$powerDist} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$powerCurveES} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$powerCurveN} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$powertab$asDF}
#'
#' \code{as.data.frame(results$powertab)}
#'
#' @export
anova <- function(
    lev_fac_a = 3,
    lev_fac_b = 0,
    lev_fac_c = 0,
    type_fac_a = "b",
    type_fac_b = "b",
    type_fac_c = "b",
    estype = "f",
    es = 0.3,
    power = 0.8,
    n = 20,
    k = 3,
    alpha = 0.05,
    powerDist = TRUE,
    powerCurveES = FALSE,
    powerCurveN = FALSE,
    num_facs = "one") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("anova requires jmvcore to be installed (restart may be required)")


    options <- anovaOptions$new(
        lev_fac_a = lev_fac_a,
        lev_fac_b = lev_fac_b,
        lev_fac_c = lev_fac_c,
        type_fac_a = type_fac_a,
        type_fac_b = type_fac_b,
        type_fac_c = type_fac_c,
        estype = estype,
        es = es,
        power = power,
        n = n,
        k = k,
        alpha = alpha,
        powerDist = powerDist,
        powerCurveES = powerCurveES,
        powerCurveN = powerCurveN,
        num_facs = num_facs)

    analysis <- anovaClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

