
# This file is automatically generated, you probably don't want to edit this

muANOVAOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "muANOVAOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            lev_fac_a = 3,
            lev_fac_b = 2,
            lev_fac_c = 2,
            type_fac_a = "b",
            type_fac_b = "b",
            type_fac_c = "b",
            n = 20,
            alpha = 0.05,
            stdev = 1,
            withcorr = 0,
            num_facs = "one",
            powerDist = FALSE,
            powerCurveES = FALSE,
            powerCurveN = FALSE,
            power = 0.8, ...) {

            super$initialize(
                package="jpower",
                name="muANOVA",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"),
                rejectInf=TRUE)
            private$..lev_fac_a <- jmvcore::OptionInteger$new(
                "lev_fac_a",
                lev_fac_a,
                min=2,
                default=3)
            private$..lev_fac_b <- jmvcore::OptionInteger$new(
                "lev_fac_b",
                lev_fac_b,
                min=2,
                max=99,
                default=2)
            private$..lev_fac_c <- jmvcore::OptionInteger$new(
                "lev_fac_c",
                lev_fac_c,
                min=2,
                max=99,
                default=2)
            private$..type_fac_a <- jmvcore::OptionList$new(
                "type_fac_a",
                type_fac_a,
                options=list(
                    "b",
                    "w"),
                default="b")
            private$..type_fac_b <- jmvcore::OptionList$new(
                "type_fac_b",
                type_fac_b,
                options=list(
                    "b",
                    "w"),
                default="b")
            private$..type_fac_c <- jmvcore::OptionList$new(
                "type_fac_c",
                type_fac_c,
                options=list(
                    "b",
                    "w"),
                default="b")
            private$..n <- jmvcore::OptionInteger$new(
                "n",
                n,
                min=2,
                default=20)
            private$..alpha <- jmvcore::OptionNumber$new(
                "alpha",
                alpha,
                min=0,
                default=0.05)
            private$..stdev <- jmvcore::OptionNumber$new(
                "stdev",
                stdev,
                min=1e-23,
                default=1)
            private$..withcorr <- jmvcore::OptionNumber$new(
                "withcorr",
                withcorr,
                min=-1,
                max=1,
                default=0)
            private$..num_facs <- jmvcore::OptionList$new(
                "num_facs",
                num_facs,
                options=list(
                    "one",
                    "two",
                    "three"),
                default="one")
            private$..powerDist <- jmvcore::OptionBool$new(
                "powerDist",
                powerDist,
                default=FALSE)
            private$..powerCurveES <- jmvcore::OptionBool$new(
                "powerCurveES",
                powerCurveES,
                default=FALSE)
            private$..powerCurveN <- jmvcore::OptionBool$new(
                "powerCurveN",
                powerCurveN,
                default=FALSE)
            private$..power <- jmvcore::OptionNumber$new(
                "power",
                power,
                min=0,
                max=1,
                default=0.8)

            self$.addOption(private$..dep)
            self$.addOption(private$..lev_fac_a)
            self$.addOption(private$..lev_fac_b)
            self$.addOption(private$..lev_fac_c)
            self$.addOption(private$..type_fac_a)
            self$.addOption(private$..type_fac_b)
            self$.addOption(private$..type_fac_c)
            self$.addOption(private$..n)
            self$.addOption(private$..alpha)
            self$.addOption(private$..stdev)
            self$.addOption(private$..withcorr)
            self$.addOption(private$..num_facs)
            self$.addOption(private$..powerDist)
            self$.addOption(private$..powerCurveES)
            self$.addOption(private$..powerCurveN)
            self$.addOption(private$..power)
        }),
    active = list(
        dep = function() private$..dep$value,
        lev_fac_a = function() private$..lev_fac_a$value,
        lev_fac_b = function() private$..lev_fac_b$value,
        lev_fac_c = function() private$..lev_fac_c$value,
        type_fac_a = function() private$..type_fac_a$value,
        type_fac_b = function() private$..type_fac_b$value,
        type_fac_c = function() private$..type_fac_c$value,
        n = function() private$..n$value,
        alpha = function() private$..alpha$value,
        stdev = function() private$..stdev$value,
        withcorr = function() private$..withcorr$value,
        num_facs = function() private$..num_facs$value,
        powerDist = function() private$..powerDist$value,
        powerCurveES = function() private$..powerCurveES$value,
        powerCurveN = function() private$..powerCurveN$value,
        power = function() private$..power$value),
    private = list(
        ..dep = NA,
        ..lev_fac_a = NA,
        ..lev_fac_b = NA,
        ..lev_fac_c = NA,
        ..type_fac_a = NA,
        ..type_fac_b = NA,
        ..type_fac_c = NA,
        ..n = NA,
        ..alpha = NA,
        ..stdev = NA,
        ..withcorr = NA,
        ..num_facs = NA,
        ..powerDist = NA,
        ..powerCurveES = NA,
        ..powerCurveN = NA,
        ..power = NA)
)

muANOVAResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "muANOVAResults",
    inherit = jmvcore::Group,
    active = list(
        designtab = function() private$.items[["designtab"]],
        main = function() private$.items[["main"]],
        DesPlot = function() private$.items[["DesPlot"]],
        powerDist = function() private$.items[["powerDist"]],
        powerCurveES = function() private$.items[["powerCurveES"]],
        powerCurveN = function() private$.items[["powerCurveN"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Factorial ANOVA")
            self$add(jmvcore::Table$new(
                options=options,
                name="designtab",
                title="Design",
                rows=1,
                clearWith=list(
                    "lev_fac_a",
                    "lev_fac_b",
                    "lev_fac_c",
                    "type_fac_a",
                    "type_fac_b",
                    "type_fac_c",
                    "n"),
                columns=list(
                    list(
                        `name`="var[type]", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="var[des]", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="var[n]", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="var[n_obs]", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="var[n_tot]", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="val[type]", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="val[des]", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="val[n]", 
                        `title`="", 
                        `type`="integer"),
                    list(
                        `name`="val[n_obs]", 
                        `title`="", 
                        `type`="integer"),
                    list(
                        `name`="val[n_tot]", 
                        `title`="", 
                        `type`="integer"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="main",
                title="Factorial ANOVA Power Analysis",
                clearWith=list(
                    "estype",
                    "es",
                    "n",
                    "alpha",
                    "lev_fac_c",
                    "lev_fac_b",
                    "lev_fac_a",
                    "type_fac_c",
                    "type_fac_b",
                    "type_fac_a",
                    "num_facs"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="num_df", 
                        `title`="Numerator DF", 
                        `type`="integer"),
                    list(
                        `name`="den_df", 
                        `title`="Denominator DF", 
                        `type`="integer"),
                    list(
                        `name`="cohen_f", 
                        `title`="Cohen's f", 
                        `type`="number"),
                    list(
                        `name`="alpha_level", 
                        `title`="Alpha Level", 
                        `type`="number"),
                    list(
                        `name`="power", 
                        `title`="Power (1-Beta)", 
                        `type`="number"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="DesPlot",
                title="Plot of Design",
                width=600,
                height=600,
                renderFun=".DesPlot",
                clearWith=list(
                    "dep",
                    "num_facs",
                    "alpha",
                    "lev_fac_c",
                    "lev_fac_b",
                    "lev_fac_a",
                    "type_fac_c",
                    "type_fac_b",
                    "type_fac_a")))
            self$add(jmvcore::Image$new(
                options=options,
                name="powerDist",
                title="Power Demonstration",
                width=600,
                height=600,
                renderFun=".powerDist",
                visible="(powerDist)",
                clearWith=list(
                    "dep",
                    "num_facs",
                    "alpha",
                    "lev_fac_c",
                    "lev_fac_b",
                    "lev_fac_a",
                    "type_fac_c",
                    "type_fac_b",
                    "type_fac_a")))
            self$add(jmvcore::Image$new(
                options=options,
                name="powerCurveES",
                title="Power Curve by Effect Size",
                width=600,
                height=600,
                renderFun=".powerCurveES",
                visible="(powerCurveES)",
                clearWith=list(
                    "estype",
                    "es",
                    "power",
                    "lev_fac_c",
                    "lev_fac_b",
                    "lev_fac_a",
                    "type_fac_c",
                    "type_fac_b",
                    "type_fac_a",
                    "alpha")))
            self$add(jmvcore::Image$new(
                options=options,
                name="powerCurveN",
                title="Power Curve by N",
                width=600,
                height=600,
                renderFun=".powerCurveN",
                visible="(powerCurveN)",
                clearWith=list(
                    "estype",
                    "es",
                    "power",
                    "lev_fac_c",
                    "lev_fac_b",
                    "lev_fac_a",
                    "type_fac_c",
                    "type_fac_b",
                    "type_fac_a",
                    "alpha",
                    "dep")))}))

muANOVABase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "muANOVABase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jpower",
                name = "muANOVA",
                version = c(1,0,0),
                options = options,
                results = muANOVAResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Factorial ANOVA
#'
#' 
#' @param data .
#' @param dep .
#' @param lev_fac_a .
#' @param lev_fac_b .
#' @param lev_fac_c .
#' @param type_fac_a .
#' @param type_fac_b .
#' @param type_fac_c .
#' @param n .
#' @param alpha .
#' @param stdev .
#' @param withcorr .
#' @param num_facs .
#' @param powerDist .
#' @param powerCurveES .
#' @param powerCurveN .
#' @param power .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$designtab} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$main} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$DesPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$powerDist} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$powerCurveES} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$powerCurveN} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$designtab$asDF}
#'
#' \code{as.data.frame(results$designtab)}
#'
#' @export
muANOVA <- function(
    data,
    dep,
    lev_fac_a = 3,
    lev_fac_b = 2,
    lev_fac_c = 2,
    type_fac_a = "b",
    type_fac_b = "b",
    type_fac_c = "b",
    n = 20,
    alpha = 0.05,
    stdev = 1,
    withcorr = 0,
    num_facs = "one",
    powerDist = FALSE,
    powerCurveES = FALSE,
    powerCurveN = FALSE,
    power = 0.8) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("muANOVA requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL))


    options <- muANOVAOptions$new(
        dep = dep,
        lev_fac_a = lev_fac_a,
        lev_fac_b = lev_fac_b,
        lev_fac_c = lev_fac_c,
        type_fac_a = type_fac_a,
        type_fac_b = type_fac_b,
        type_fac_c = type_fac_c,
        n = n,
        alpha = alpha,
        stdev = stdev,
        withcorr = withcorr,
        num_facs = num_facs,
        powerDist = powerDist,
        powerCurveES = powerCurveES,
        powerCurveN = powerCurveN,
        power = power)

    analysis <- muANOVAClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

