
# This file is automatically generated, you probably don't want to edit this

#' @importFrom jmvcore Options
#' @importFrom R6 R6Class
ttestISOptions <- R6::R6Class(
    "ttestISOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            es = 0.5,
            power = 0.8,
            n = 20,
            alt = "two-tailed",
            alpha = 0.05,
            plotby = "Effect size", ...) {

            super$initialize(
                package='jpower',
                name='ttestIS',
                requiresData=TRUE,
                ...)
        
            private$..es <- jmvcore::OptionNumber$new(
                "es",
                es,
                min=0,
                default=0.5)
            private$..power <- jmvcore::OptionNumber$new(
                "power",
                power,
                min=0,
                max=1,
                default=0.8)
            private$..n <- jmvcore::OptionInteger$new(
                "n",
                n,
                min=2,
                default=20)
            private$..alt <- jmvcore::OptionList$new(
                "alt",
                alt,
                options=list(
                    "two-tailed",
                    "one-tailed, positive",
                    "one-tailed, negative"),
                default="two-tailed")
            private$..alpha <- jmvcore::OptionNumber$new(
                "alpha",
                alpha,
                min=0,
                default=0.05)
            private$..plotby <- jmvcore::OptionList$new(
                "plotby",
                plotby,
                options=list(
                    "Effect size",
                    "Sample size",
                    "&alpha; (type I error rate)"),
                default="Effect size")
        
            self$.addOption(private$..es)
            self$.addOption(private$..power)
            self$.addOption(private$..n)
            self$.addOption(private$..alt)
            self$.addOption(private$..alpha)
            self$.addOption(private$..plotby)
        }),
    active = list(
        es = function() private$..es$value,
        power = function() private$..power$value,
        n = function() private$..n$value,
        alt = function() private$..alt$value,
        alpha = function() private$..alpha$value,
        plotby = function() private$..plotby$value),
    private = list(
        ..es = NA,
        ..power = NA,
        ..n = NA,
        ..alt = NA,
        ..alpha = NA,
        ..plotby = NA)
)

#' @import jmvcore
#' @importFrom R6 R6Class
ttestISResults <- R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        powertab = function() private$..powertab,
        powercurve = function() private$..powercurve),
    private = list(
        ..powertab = NA,
        ..powercurve = NA),
    public=list(
        initialize=function(options) {
            super$initialize(options=options, name="", title="Independent Samples T-Test")
            private$..powertab <- jmvcore::Table$new(
                options=options,
                name="powertab",
                title="A priori power analysis",
                rows=4,
                columns=list(
                    list(`name`="var", `title`="", `type`="text"),
                    list(`name`="val", `type`="number", `title`="")))
            private$..powercurve <- jmvcore::Image$new(
                options=options,
                name="powercurve",
                title="Power curve",
                width=400,
                height=300,
                renderFun=".plot")
            self$add(private$..powertab)
            self$add(private$..powercurve)}))

#' @importFrom jmvcore Analysis
#' @importFrom R6 R6Class
ttestISBase <- R6::R6Class(
    "ttestISBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'jpower',
                name = 'ttestIS',
                version = c(1,0,0),
                options = options,
                results = ttestISResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL)
        }))

#' Independent Samples T-Test
#'
#' 
#' @param es .
#' @param power .
#' @param n .
#' @param alt .
#' @param alpha .
#' @param plotby .
#' @export
ttestIS <- function(
    es = 0.5,
    power = 0.8,
    n = 20,
    alt = "two-tailed",
    alpha = 0.05,
    plotby = "Effect size") {

    options <- ttestISOptions$new(
        es = es,
        power = power,
        n = n,
        alt = alt,
        alpha = alpha,
        plotby = plotby)

    results <- ttestISResults$new(
        options = options)

    analysis <- ttestISClass$new(
        options = options,
        data = data)

    analysis$run()
    analysis$render()

    analysis
}
