
# This file is automatically generated, you probably don't want to edit this

#' @importFrom jmvcore Options
#' @importFrom R6 R6Class
ttestISOptions <- R6::R6Class(
    "ttestISOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            es = 0.5,
            power = 0.8,
            n1 = 20,
            n2 = 20,
            alt = "two tailed", ...) {

            super$initialize(
                package='jpower',
                name='ttestIS',
                requiresData=TRUE,
                ...)
        
            private$..es <- jmvcore::Optionnumber$new(
                "es",
                es,
                min=0,
                max=5,
                default=0.5)
            private$..power <- jmvcore::Optionnumber$new(
                "power",
                power,
                min=0,
                max=1,
                default=0.8)
            private$..n1 <- jmvcore::Optioninteger$new(
                "n1",
                n1,
                min=2,
                max=10000,
                default=20)
            private$..n2 <- jmvcore::Optioninteger$new(
                "n2",
                n2,
                min=2,
                max=10000,
                default=20)
            private$..alt <- jmvcore::OptionList$new(
                "alt",
                alt,
                options=list(
                    "two tailed",
                    "one tailed"),
                default="two tailed")
        
            self$.addOption(private$..es)
            self$.addOption(private$..power)
            self$.addOption(private$..n1)
            self$.addOption(private$..n2)
            self$.addOption(private$..alt)
        }),
    active = list(
        es = function() private$..es$value,
        power = function() private$..power$value,
        n1 = function() private$..n1$value,
        n2 = function() private$..n2$value,
        alt = function() private$..alt$value),
    private = list(
        ..es = NA,
        ..power = NA,
        ..n1 = NA,
        ..n2 = NA,
        ..alt = NA)
)

#' @import jmvcore
#' @importFrom R6 R6Class
ttestISResults <- R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        text = function() private$..text),
    private = list(
        ..text = NA),
    public=list(
        initialize=function(options) {
            super$initialize(options=options, name="", title="Independent Samples T-Test")
            private$..text <- jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Independent Samples T-Test")
            self$add(private$..text)}))

#' @importFrom jmvcore Analysis
#' @importFrom R6 R6Class
ttestISBase <- R6::R6Class(
    "ttestISBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'jpower',
                name = 'ttestIS',
                version = c(1,0,0),
                options = options,
                results = ttestISResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL)
        }))

#' Independent Samples T-Test
#'
#' 
#' @param es .
#' @param power .
#' @param n1 .
#' @param n2 .
#' @param alt .
#' @export
ttestIS <- function(
    es = 0.5,
    power = 0.8,
    n1 = 20,
    n2 = 20,
    alt = "two tailed") {

    options <- ttestISOptions$new(
        es = es,
        power = power,
        n1 = n1,
        n2 = n2,
        alt = alt)

    results <- ttestISResults$new(
        options = options)

    analysis <- ttestISClass$new(
        options = options,
        data = data)

    analysis$run()
    analysis$render()

    analysis
}
