
# This file is automatically generated, you probably don't want to edit this

#' @importFrom jmvcore Options
#' @importFrom R6 R6Class
ttestISOptions <- R6::R6Class(
    "ttestISOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            es = 0.5,
            power = 0.8,
            n = 20,
            alt = "two-tailed",
            alpha = 0.05,
            powerDist = TRUE,
            powerCurveES = FALSE,
            powerCurveN = FALSE, ...) {

            super$initialize(
                package='jpower',
                name='ttestIS',
                requiresData=TRUE,
                ...)
        
            private$..es <- jmvcore::OptionNumber$new(
                "es",
                es,
                min=0.01,
                default=0.5)
            private$..power <- jmvcore::OptionNumber$new(
                "power",
                power,
                min=0,
                max=1,
                default=0.8)
            private$..n <- jmvcore::OptionInteger$new(
                "n",
                n,
                min=2,
                default=20)
            private$..alt <- jmvcore::OptionList$new(
                "alt",
                alt,
                options=list(
                    "two-tailed",
                    "one-tailed, positive",
                    "one-tailed, negative"),
                default="two-tailed")
            private$..alpha <- jmvcore::OptionNumber$new(
                "alpha",
                alpha,
                min=0,
                default=0.05)
            private$..powerDist <- jmvcore::OptionBool$new(
                "powerDist",
                powerDist,
                default=TRUE)
            private$..powerCurveES <- jmvcore::OptionBool$new(
                "powerCurveES",
                powerCurveES,
                default=FALSE)
            private$..powerCurveN <- jmvcore::OptionBool$new(
                "powerCurveN",
                powerCurveN,
                default=FALSE)
        
            self$.addOption(private$..es)
            self$.addOption(private$..power)
            self$.addOption(private$..n)
            self$.addOption(private$..alt)
            self$.addOption(private$..alpha)
            self$.addOption(private$..powerDist)
            self$.addOption(private$..powerCurveES)
            self$.addOption(private$..powerCurveN)
        }),
    active = list(
        es = function() private$..es$value,
        power = function() private$..power$value,
        n = function() private$..n$value,
        alt = function() private$..alt$value,
        alpha = function() private$..alpha$value,
        powerDist = function() private$..powerDist$value,
        powerCurveES = function() private$..powerCurveES$value,
        powerCurveN = function() private$..powerCurveN$value),
    private = list(
        ..es = NA,
        ..power = NA,
        ..n = NA,
        ..alt = NA,
        ..alpha = NA,
        ..powerDist = NA,
        ..powerCurveES = NA,
        ..powerCurveN = NA)
)

#' @import jmvcore
#' @importFrom R6 R6Class
ttestISResults <- R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        powertab = function() private$..powertab,
        powerDist = function() private$..powerDist,
        powerCurveES = function() private$..powerCurveES,
        powerCurveN = function() private$..powerCurveN),
    private = list(
        ..powertab = NA,
        ..powerDist = NA,
        ..powerCurveES = NA,
        ..powerCurveN = NA),
    public=list(
        initialize=function(options) {
            super$initialize(options=options, name="", title="Independent Samples T test")
            private$..powertab <- jmvcore::Table$new(
                options=options,
                name="powertab",
                title="A Priori Power Analysis",
                rows=1,
                clearWith=list(
                    "es",
                    "power",
                    "n",
                    "alt",
                    "alpha"),
                columns=list(
                    list(`name`="var[n]", `title`="", `type`="text"),
                    list(`name`="var[es]", `title`="", `type`="text"),
                    list(`name`="var[power]", `title`="", `type`="text"),
                    list(`name`="var[alpha]", `title`="", `type`="text"),
                    list(`name`="val[n]", `title`="", `type`="integer"),
                    list(`name`="val[es]", `title`="", `type`="number"),
                    list(`name`="val[power]", `title`="", `type`="number"),
                    list(`name`="val[alpha]", `title`="", `type`="number")))
            private$..powerDist <- jmvcore::Image$new(
                options=options,
                name="powerDist",
                title="Power Demonstration",
                width=400,
                height=300,
                renderFun=".powerDist",
                visible="(powerDist)",
                clearWith=list(
                    "es",
                    "power",
                    "n",
                    "alt",
                    "alpha"))
            private$..powerCurveES <- jmvcore::Image$new(
                options=options,
                name="powerCurveES",
                title="Power Curve by Effect Size",
                width=400,
                height=300,
                renderFun=".powerCurveES",
                visible="(powerCurveES)",
                clearWith=list(
                    "es",
                    "power",
                    "n",
                    "alt",
                    "alpha"))
            private$..powerCurveN <- jmvcore::Image$new(
                options=options,
                name="powerCurveN",
                title="Power Curve by N",
                width=400,
                height=300,
                renderFun=".powerCurveN",
                visible="(powerCurveN)",
                clearWith=list(
                    "es",
                    "power",
                    "n",
                    "alt",
                    "alpha"))
            self$add(private$..powertab)
            self$add(private$..powerDist)
            self$add(private$..powerCurveES)
            self$add(private$..powerCurveN)}))

#' @importFrom jmvcore Analysis
#' @importFrom R6 R6Class
ttestISBase <- R6::R6Class(
    "ttestISBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'jpower',
                name = 'ttestIS',
                version = c(1,0,0),
                options = options,
                results = ttestISResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' Independent Samples T-Test
#'
#' 
#' @param es .
#' @param power .
#' @param n .
#' @param alt .
#' @param alpha .
#' @param powerDist .
#' @param powerCurveES .
#' @param powerCurveN .
#' @export
ttestIS <- function(
    es = 0.5,
    power = 0.8,
    n = 20,
    alt = "two-tailed",
    alpha = 0.05,
    powerDist = TRUE,
    powerCurveES = FALSE,
    powerCurveN = FALSE) {

    options <- ttestISOptions$new(
        es = es,
        power = power,
        n = n,
        alt = alt,
        alpha = alpha,
        powerDist = powerDist,
        powerCurveES = powerCurveES,
        powerCurveN = powerCurveN)

    results <- ttestISResults$new(
        options = options)

    analysis <- ttestISClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
